name: Continuous Deployment - Release
on:
  push:
    tags:
      - 'v*'  # Runs on version tags like v1.0, v2.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt update -y && sudo apt install scons

    - name: Compile
      run: |
        (cd godot-cpp && scons)
        scons

    - name: Set up Godot 4
      uses: firebelley/godot-export@v6.0.0
      with:
        godot-version: '4.4.4'
        export-debug: true
        export-release: true
        use-godot-export-template: true
        relative_project_path: ./game

    - name: Create build directory
      run: mkdir -p builds/

    - name: Export for Web (WASM)
      run: |
        godot --headless --export-release "Web" "builds/libretro-godot4-frontend.wasm"
      env:
        GODOT_DEBUG: 'false'

    - name: Export for Windows
      run: |
        godot --headless --export-release "Windows Desktop" "builds/libretro-godot4-frontend.exe"

    - name: Export for Linux
      run: |
        godot --headless --export-release "Linux/X11" "builds/libretro-godot4-frontend.x86_64"

    - name: Export for macOS
      run: |
        godot --headless --export-release "macOS" "builds/libretro-godot4-frontend.zip"

    - name: Export for Android
      run: |
        godot --headless --export-release "Android" "builds/libretro-godot4-frontend.apk"

    - name: Upload Builds to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          builds/*.wasm
          builds/*.exe
          builds/*.x86_64
          builds/*.zip
          builds/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
