name: Continuous Deployment - Release
on:
  push:
    tags:
      - 'v*'  # Runs on version tags like v1.0, v2.1, etc.

jobs:
  cd:
    runs-on: ubuntu-latest
    
    # Add permission for release creation. Can be made narrower according to your needs
    permissions: write-all
    
    name: Export Game
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache SCons build artifacts
      uses: actions/cache@v4
      with:
        path: .scons_cache
        key: scons-${{ runner.os }}-${{ hashFiles('SConstruct', 'src/**', 'godot-cpp/**') }}
        restore-keys: |
          scons-${{ runner.os }}-

    - name: Cache Godot-cpp
      uses: actions/cache@v4
      with:
        path: godot-cpp/bin
        key: godotcpp-${{ runner.os }}-${{ hashFiles('godot-cpp/**') }}
        restore-keys: |
          godotcpp-${{ runner.os }}-

    - name: Cache Godot export templates
      uses: actions/cache@v4
      with:
        path: ~/.local/share/godot
        key: godot-templates-${{ runner.os }}-${{ hashFiles('game/export_presets.cfg') }}
        restore-keys: |
          godot-templates-${{ runner.os }}-

    - name: Set up dependencies
      run: |
        sudo apt update -y && sudo apt install scons

    - name: Compile godot-cpp
      run: |
        (cd godot-cpp && scons target=template_release)
    
    - name: Compile main project
      run: |
        scons target=template_release

    - name: Set up Godot 4
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
        export-release: true
        relative_project_path: ./game
        cache: true
        verbose: true

    - name: Create build directory
      run: mkdir -p builds/

    - name: Export for Web (WASM)
      run: |
        godot --headless --export-release "Web" "builds/libretro-godot4-frontend.wasm"
      env:
        GODOT_DEBUG: 'false'

    - name: Export for Windows
      run: |
        godot --headless --export-release "Windows Desktop" "builds/libretro-godot4-frontend.exe"

    - name: Export for Linux
      run: |
        godot --headless --export-release "Linux/X11" "builds/libretro-godot4-frontend.x86_64"

    - name: Export for macOS
      run: |
        godot --headless --export-release "macOS" "builds/libretro-godot4-frontend.zip"

    - name: Export for Android
      run: |
        godot --headless --export-release "Android" "builds/libretro-godot4-frontend.apk"

    - name: Upload Builds to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          builds/*.wasm
          builds/*.exe
          builds/*.x86_64
          builds/*.zip
          builds/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
